### PR TITLE
Create the ApiErrorModal

### PR DESCRIPTION
**Pull request by michho8**
# Ticket Link

[Ticket 627](https://uhawaii.atlassian.net/browse/GROUPINGS-627)

# List of squashed commits

- Link to Feedback page for the link and Report button
- Remove useHistory related code and add param to InfoModal
- Add tests
- Fix tests - don't check if Feedback page appears
- Remove React Router dependency
- Refactor as ApiErrorModal and remove from nav bar
- Change content to match ApiErrorModal
- Fix tests 

# Test Checklist

-   [x] Unit Tests Passed
-   [ ] Integration Tests Passed (N/A)
-   [x] General Visual Inspection

### CODE REVIEW

**Comment by michho8** [comment]
image
This results in an informational model where the link and the "Report" button will redirect the user to the Feedback page. The "No, thanks" button and the "X" at the top right will close the modal without redirection.

**Comment by JorWo** [comment]
This is the ApiErrorModal in our Angular.js project correct? We might want to rename it. It would be great for this modal to appear whenever an API error happens, just like in our Angular.js. Anyway, that can be the scope of another ticket. I would take it out of Navbar.tsx for now since nothing is opening the modal.

**Comment by michho8** [comment]
> This is the ApiErrorModal in our Angular.js project correct? We might want to rename it. Also, it would be great for this modal to appear whenever an API error happens, just like in our Angular.js. Anyway, that can be the scope of another ticket. I would take it out of Navbar.tsx for now since nothing is opening the modal.

I assumed this was a new model based on the different content. In the ticket, the content to be displayed is, "Oops, something went wrong. Please report this to us by sending out this form."

The ApiErrorModal has a different message:
image

If they both handle the same error, should I change the current content to match the ApiErrorModal then?

**Comment by JorWo** [comment]
> > This is the ApiErrorModal in our Angular.js project correct? We might want to rename it. Also, it would be great for this modal to appear whenever an API error happens, just like in our Angular.js. Anyway, that can be the scope of another ticket. I would take it out of Navbar.tsx for now since nothing is opening the modal.
> 
> I assumed this was a new model based on the different content. In the ticket, the content to be displayed is, "Oops, something went wrong. Please report this to us by sending out this form."
> 
> The ApiErrorModal has a different message: image
> 
> If they both handle the same error, should I change the current content to match the ApiErrorModal then?

This would be a good to bring up in a meeting.

**Comment by michho8** [comment]
image
What the modal looks like right now.

**Review by JorWo — APPROVED** [review]
Looks good!

**Pull request merged**
