### PR TITLE
Use dynamic export instead of import for GroupingsTable

### PR DESCRIPTION
**Pull request by JorWo**
# Ticket Link

[GROUPINGS-1855](https://uhawaii.atlassian.net/browse/GROUPINGS-1855)

# List of squashed commits

-   Adds missing test for groupings-table-skeleton.tsx
-   Fixes React key warning in groupings-table-skeleton.tsx
-   Fixes incorrect text and background color for copy tooltip in grouping-path-cell.tsx

# Test Checklist

-   [x] Unit Tests Passed
-   [x] General Visual Inspection

### CODE REVIEW

**Review by mhodgesatuh — COMMENTED** [review]
Some users disable cookies.  Has this been tested to see how this is handled to ensure nothing uncontrolled happens.

**Comment by JorWo** [comment]
> Some users disable cookies. Has this been tested to see how this is handled to ensure nothing uncontrolled happens.

Good point. I just tested running the site without cookies and the user is unable to make it past the CAS login anyways. This is the case for both prod and test CAS environments. I think the Duo 2FA needs cookies.

**Review by mhodgesatuh — APPROVED** [review]
Your response addresses the cookie issue as far as I'm concerned.

**Comment by JorWo** [comment]
I also tested the scenario when the user disabled cookies after logging in. Upon clicking anything, the user gets redirected to the home page.

**Pull request merged**
