### PR TITLE
Use nested layout.tsx for /admin, /memberships, /groupings

### PR DESCRIPTION
**Pull request by JorWo**
# Ticket Link

[GROUPINGS-1700](https://uhawaii.atlassian.net/browse/GROUPINGS-1700)

# List of squashed commits

-   Update Jest spy names to match files in /access
-   Move app/_components to components/layout
-   Add missing navbar.test.tsx that was accidently removed

# Test Checklist

-   [x] Unit Tests Passed
-   [x] General Visual Inspection

### CODE REVIEW

**Comment by JorWo** [comment]
Large number of diffs due to Prettier reformatting.

**Review by mhodgesatuh — APPROVED** [review]
Not sure why jest tests for AuthenticationService were changed to Authentication. The former suggests that we are testing the service implementation, or is that old (Spring Boot) thinking?  Same for GroupingsApiService dropping "Service". And there are other examples.

To future proof app best not to reference CAS.  We have a project to retire it and use only Shibboleth.  I realize this is just a test message, but good to know.

    Old: "should visit the CAS login url on click"
    New: "should visit the UH Login URL on click"

**Comment by JorWo** [comment]
> Not sure why jest tests for AuthenticationService were changed to Authentication. The former suggests that we are testing the service implementation, or is that old (Spring Boot) thinking? Same for GroupingsApiService dropping "Service". And there are other examples.
> 
> To future proof app best not to reference CAS. We have a project to retire it and use only Shibboleth. I realize this is just a test message, but good to know.
> 
> ```
> Old: "should visit the CAS login url on click"
> New: "should visit the UH Login URL on click"
> ```

I decided to take off the service because unlike Angular, services do not exist Next.js . I also thought it might be confusing for someone researching what a Next.js service is when it does not exist. Rather, these files hold what Next.js calls "server actions". Going through other Next.js projects, I have not seen any files that end with "Actions" or "ServerActions" but rather just a file that describes its purpose, for example `query.ts`, `database.ts`, `auth.ts`.

I assuming once CAS is retired for Shibboleth, this CAS client would not be sufficient anymore, so I will keep the CAS references for now. I'm still planning on separating out the CAS client to its own project, so most of the references to CAS will disappear from this project.

**Comment by mhodgesatuh** [comment]
Actually, CAS supports the CAS3 authentication protocol.  So does Shib, so your assumption doesn't actual work.  Currently, we use Shib for SAML, but in the future it will be both SAML and CAS3, and likely OIDC too.

**Comment by JorWo** [comment]
That's good to know, I was thinking the CAS client will be wiped away. I will be focusing on the moving the CAS client into a dependency next.

**Pull request merged**
